name: CI

# Controls when the action will run. 
on:
  # 任意推送都会触发构建
  push:
# 定时调度
  schedule:
    - cron: "0 0 * * 1"

  # Allows you to run this workflow manually from the Actions tab
# 可以手动触发
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'   
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'  

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      - name: Get current date
        id: date
        run: echo "::set-output name=today::$(date +'%Y%m%d')"
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      -
        name: 查看可用平台
        run: echo ${{ steps.buildx.outputs.platforms }}
      -
        name: 登录阿里云容器
        uses: docker/login-action@v1
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_PASSWORD }}
      -
        name: 登录 DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: 构建并推送
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
# 所需要的体系结构，可以在 Available platforms 步骤中获取所有的可用架构
          platforms: linux/amd64
# 镜像推送时间
          push: ${{ github.event_name != 'pull_request' }}
# 给清单打上多个标签
          tags: |
            tossp/jellyfin:latest
            tossp/jellyfin:${{ steps.date.outputs.today }} 
            registry.cn-hangzhou.aliyuncs.com/tossp/jellyfin:latest
            registry.cn-hangzhou.aliyuncs.com/tossp/jellyfin:${{ steps.date.outputs.today }} 
      - name: 删除旧的工作流
        uses: GitRML/delete-workflow-runs@main
        with:
          retain_days: 1
          keep_minimum_runs: 3
